### ISSUE TITLE
server exit 2024/07/03

### ISSUE THREAD

**Issue by moeyashi** [moeyashi/discord-mk8d-nita-record#156]
# log

```
2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] /layers/paketo-buildpacks_npm-install/launch-modules/node_modules/discord.js/src/structures/BaseInteraction.js:106

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] this.entitlements = data.entitlements.reduce(

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] ^

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] TypeError: Cannot read properties of undefined (reading 'reduce')

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] at new BaseInteraction (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/discord.js/src/structures/BaseInteraction.js:106:43)

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] at new CommandInteraction (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/discord.js/src/structures/CommandInteraction.js:16:5)

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] at new ChatInputCommandInteraction (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/discord.js/src/structures/ChatInputCommandInteraction.js:13:5)

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] at InteractionCreateAction.handle (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/discord.js/src/client/actions/InteractionCreate.js:90:25)

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] at module.exports [as INTERACTION_CREATE] (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/discord.js/src/client/websocket/handlers/INTERACTION_CREATE.js:4:36)

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] at WebSocketManager.handlePacket (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/discord.js/src/client/websocket/WebSocketManager.js:355:31)

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] at WebSocketManager.<anonymous> (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/discord.js/src/client/websocket/WebSocketManager.js:239:12)

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] at WebSocketManager.emit (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:282:31)

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] at WebSocketShard.<anonymous> (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@discordjs/ws/dist/index.js:1190:51)

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] at WebSocketShard.emit (/layers/paketo-buildpacks_npm-install/launch-modules/node_modules/@vladfrangu/async_event_emitter/dist/index.cjs:282:31)

2024-07-03T00:50:17.968 app[91852e3ea2d108] nrt [info] Node.js v20.15.0

2024-07-03T00:50:18.504 app[91852e3ea2d108] nrt [info] INFO Main child exited normally with code: 1
```

**Comment by moeyashi** [comment]
https://github.com/discordjs/discord.js/issues/10377
